name: signbase
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  google_ml_kit: ^0.16.2
  google_mlkit_image_labeling: ^0.9.0
  speech_to_text: ^6.3.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^10.4.3
  share_plus: ^7.1.0
  path_provider: ^2.1.1
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/images_alphabets/
    - assets/images/images_domestic_animals/
    - assets/images/images_flowers/
    - assets/images/images_birds/
    - assets/images/images_colors/
    - assets/images/images_fruits/
    - assets/images/images_gadgets/
    - assets/images/images_music_inst/
    - assets/images/images_seasons/
    - assets/images/images_shapes/
    - assets/images/images_vegetables/
    - assets/images/images_vehicles/
    - assets/images/images_water_animals/
    - assets/images/images_wild_animals/
    - assets/images/images_relatives/
    - assets/images/dataset/
    - assets/images/dataset/alphabets/
    - assets/images/dataset/numbers/
    - assets/font/

  fonts:
    - family: Martel
      fonts:
        - asset: assets/font/Martel-Regular.ttf
